# Shell variables
# Generated by 'wal'
wallpaper='/home/abancp/Pictures/wallpapers/Dynamic-Wallpapers/Dark/Beach-Dark.png'

# Special
background='#050308'
foreground='#d0a7c7'
cursor='#d0a7c7'

# Colors
color0='#050308'
color1='#3D02BD'
color2='#4D0EB5'
color3='#6B2CA7'
color4='#5C07D7'
color5='#5321C4'
color6='#9B5591'
color7='#d0a7c7'
color8='#91748b'
color9='#3D02BD'
color10='#4D0EB5'
color11='#6B2CA7'
color12='#5C07D7'
color13='#5321C4'
color14='#9B5591'
color15='#d0a7c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
