--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/abancp/Pictures/wallpapers/Dynamic-Wallpapers/Dark/Beach-Dark.png"

-- Special
background="#050308"
foreground="#d0a7c7"
cursor="#d0a7c7"

-- Colors
color0="#050308"
color1="#3D02BD"
color2="#4D0EB5"
color3="#6B2CA7"
color4="#5C07D7"
color5="#5321C4"
color6="#9B5591"
color7="#d0a7c7"
color8="#91748b"
color9="#3D02BD"
color10="#4D0EB5"
color11="#6B2CA7"
color12="#5C07D7"
color13="#5321C4"
color14="#9B5591"
color15="#d0a7c7"
